name: Build Crunch Tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpng-dev

      - name: Clone crunch repository
        run: |
          git clone https://github.com/DaemonEngine/crunch.git
          cd crunch
          git submodule update --init --recursive

      - name: Build crunch
        run: |
          cd crunch
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crunch-linux-x64
          path: crunch/build/crunch
