name: Sync Slide

on:
  workflow_dispatch:
    inputs:
      slides:
        description: 'Slides config in JSON format. Example: [{"type":"sample","url":"https://docs.google.com/presentation/d/xxx"}, ...]'
        required: true
        type: string
#  repository_dispatch:
#    types: [on-demand-sync-drive-files]

env:
  TEMP_IMAGES: temp-images
  TEMP_IMAGES_CRUNCHED: temp-images-crunched

jobs:
  sync-slide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create service account JSON file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install packages
        run: |
          npm install google-auth-library googleapis
        shell: bash

      - name: Setup Output Directory
        run: |
          mkdir -p ${{ env.TEMP_IMAGES }}
          mkdir -p ${{ env.TEMP_IMAGES_CRUNCHED }}

      - name: Download slides as images
        env:
          SERVICE_ACCOUNT_JSON_PATH: "./service-account.json"
          SLIDES_CONFIG: ${{ inputs.slides }}
          TEMP_DIR: ${{ env.TEMP_IMAGES }}
        run: |
          mkdir -p $TEMP_DIR
          node ./scripts/download-slides.js

      - name: Upload exported files
        uses: actions/upload-artifact@v4
        with:
          name: temp-images
          path: ${{ env.TEMP_IMAGES }}

      - name: Crunch images
        uses: tp-jp/unity-export-crunched-action@main
        with:
          input-path: ${{ env.TEMP_IMAGES }}
          output-path: ${{ env.TEMP_IMAGES_CRUNCHED }}
          unity-email: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-license: ${{ secrets.UNITY_LICENSE }}
          unity-version: "2022.3.22f1"
          max-size: 2048
          compression-quality: 50

      - name: Upload exported files
        uses: actions/upload-artifact@v4
        with:
          name: crunched-textures
          path: ${{ env.TEMP_IMAGES_CRUNCHED }}

      # - name: Check for changes
      #   run: |
      #     git config --global user.email "action@github.com"
      #     git config --global user.name "GitHub Action"

      #     git add --all

      #     if ! git diff-index --quiet HEAD --; then
      #       git commit -m "Update images from Google Drive"
      #       git push
      #     else
      #       echo "No changes to commit."
      #     fi
