name: Sync Slide

on:
  repository_dispatch:
    types: [sync-slides]

env:
  TEMP_IMAGES: temp-images
  TEMP_IMAGES_CRUNCHED: temp-images-crunched

jobs:
  sync-slide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create service account JSON file
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service-account.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install packages
        run: |
          npm install
        shell: bash

      - name: Download slides as images
        env:
          SERVICE_ACCOUNT_JSON_PATH: "./service-account.json"
          SLIDES_CONFIG: ${{ toJSON(github.event.client_payload.slides) }}
          TEMP_DIR: ${{ env.TEMP_IMAGES }}
        run: |
          mkdir -p $TEMP_DIR
          node ./scripts/download-slides.js

      - name: Crunch images
        uses: tp-jp/unity-export-crunched-action@v1
        with:
          input-path: ${{ env.TEMP_IMAGES }}
          output-path: ${{ env.TEMP_IMAGES_CRUNCHED }}
          unity-email: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-license: ${{ secrets.UNITY_LICENSE }}
          unity-version: "2022.3.22f1"
          max-size: "2048"
          compression-quality: "50"

      - name: Upload crunched images
        uses: actions/upload-artifact@v4
        with:
          name: crunched-images
          path: ${{ env.TEMP_IMAGES_CRUNCHED }}

      - name: Combine images as Base64
        env:
          INPUT_DIR: ${{ env.TEMP_IMAGES_CRUNCHED }}
          OUTPUT_DIR: "./public/slides"
        run: |
          mkdir -p $OUTPUT_DIR
          rm -rf $OUTPUT_DIR/*
          node ./scripts/combine-images-base64.js

      - name: Check for changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git add --all

          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update slides"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Notify completion
        if: always()
        run: |
          status="${{ job.status == 'success' && 'completed' || 'failed' }}"
          error="${{ job.status != 'success' && job.status || '' }}"

          curl -X POST ${{ secrets.APP_URL }}/api/slides/sync/webhook \
            -H "Content-Type: application/json" \
            -d "{\"syncId\": \"${{ github.event.client_payload.syncId }}\", \"status\": \"$status\", \"error\": \"$error\"}"

      - name: Upload exported images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: ${{ env.TEMP_IMAGES }}

      - name: Upload exported crunched images
        uses: actions/upload-artifact@v4
        with:
          name: crunched-images
          path: ${{ env.TEMP_IMAGES_CRUNCHED }}
